export const queryKeys = {
  me: ['me'] as const,
  dashboard: ['dashboard'] as const,
  categories: ['categories'] as const,
  category: (id: string) => ['categories', id] as const,
  ingredients: ['ingredients'] as const,
  products: (params?: object) => ['products', params] as const,
  product: (id: string) => ['products', id] as const,
  orders: (params?: object) => ['orders', params] as const,
  order: (id: string) => ['orders', id] as const,
  reviews: (params?: object) => ['reviews', params] as const,
  customers: (params?: object) => ['customers', params] as const,
  customer: (id: string) => ['customers', id] as const,
  roles: ['roles'] as const,
  permissions: ['permissions'] as const,
  adminUsers: ['admin-users'] as const,

  // Back office (procurement)
  vendors: (params?: object) => ['vendors', params] as const,
  vendor: (id: string) => ['vendors', id] as const,
  rawMaterials: (params?: object) => ['raw-materials', params] as const,
  rawMaterial: (id: string) => ['raw-materials', id] as const,

  // Phase 2
  media: (params?: object) => ['media', params] as const,
  banners: ['banners'] as const,
  cmsPages: ['cms-pages'] as const,
  cmsPage: (slug: string) => ['cms-pages', slug] as const,
  blogs: ['blogs'] as const,
  blog: (id: string) => ['blogs', id] as const,
  faqs: ['faqs'] as const,
  recipes: ['recipes'] as const,
  recipe: (id: string) => ['recipes', id] as const,
  tickets: (params?: object) => ['tickets', params] as const,
  ticket: (id: string) => ['tickets', id] as const,
  settings: ['settings'] as const,
};
